import {test,expect} from '@playwright/test';
import {loadCorpus} from './support/catalogue.mjs';
test.skip(!process.env.GI_UX_LINKS,'Requires native stored links; use make test-ux-links');
const inputName='Message (Enter to send, Shift+Enter for newline)...';
test('@ux-timeline-025 native resource and preview links use isolated new tabs',async({page,request,context},info)=>{
 const s=loadCorpus().find(s=>s.id==='@ux-timeline-025');await info.attach('gherkin',{body:s.steps.join('\n'),contentType:'text/plain'});
 const id='links-fixture',before=(await(await request.get(`/api/sessions/${id}/messages`)).json()).messages;expect(before).toHaveLength(1);expect(before[0].payload.content_blocks[0].uri).toContain('resource.example.invalid');
 const remote=[];await context.route(/^https?:\/\/[^/]+\.example\.invalid\//,async route=>{remote.push({url:route.request().url(),referer:route.request().headers().referer||null});await route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><title>Local navigation proof</title><p>destination</p>'});});
 await page.addInitScript(id=>localStorage.setItem('gi_session_id',id),id);await page.goto('/');const input=page.getByRole('textbox',{name:inputName,exact:true});await input.fill('link draft β');await page.locator('.compose-box input[type=file]').setInputFiles({name:'link-ref.txt',mimeType:'text/plain',buffer:Buffer.from('preserved link attachment')});
 const post=page.locator('[id="post-links-message"]');await expect(post).toBeVisible();await expect(post.locator('.post-content')).toContainText(before[0].content);await expect(post.locator('.resource-link')).toHaveCount(1);await expect(post.locator('.link-preview')).toHaveCount(1);await expect(post).not.toContainText('Unsafe');await expect(post.locator('.link-preview-image')).toHaveCount(0);expect(remote).toEqual([]);
 for(const [selector,url]of [['.resource-link','https://resource.example.invalid/report?q=beta'],['.link-preview','http://preview.example.invalid/article']]){
  const link=post.locator(selector);await expect(link).toHaveAttribute('href',url);await expect(link).toHaveAttribute('target','_blank');await expect(link).toHaveAttribute('rel','noopener noreferrer');
  const popupPromise=context.waitForEvent('page');if(selector==='.resource-link')await link.click();else{await link.focus();await link.press('Enter');}const popup=await popupPromise;try{await popup.waitForLoadState();expect(popup.url()).toBe(url);expect(await popup.evaluate(()=>window.opener===null)).toBe(true);}finally{await popup.close();}
  expect(remote.at(-1)).toEqual({url,referer:null});await expect(input).toHaveValue('link draft β');await expect(page.locator('.compose-box')).toContainText('link-ref.txt');expect(await page.evaluate(()=>localStorage.getItem('gi_session_id'))).toBe(id);
 }
 await page.reload();await expect(post.locator('.resource-link')).toHaveCount(1);await expect(post.locator('.link-preview')).toHaveCount(1);await expect(input).toHaveValue('link draft β');await expect(page.locator('.compose-box')).toContainText('link-ref.txt');
 await page.getByRole('button',{name:'Search',exact:true}).click();const search=page.getByRole('textbox',{name:'Search (Enter to run)...',exact:true});await search.fill('remote-link');const found=page.waitForResponse(r=>r.url().includes('/search?')&&r.status()===200);await search.press('Enter');await found;await expect(post.locator('.resource-link')).toHaveAttribute('rel','noopener noreferrer');await expect(post.locator('.link-preview')).toHaveAttribute('rel','noopener noreferrer');expect(remote).toHaveLength(2);
 const popupPromise=context.waitForEvent('page');await post.locator('.link-preview').click();const popup=await popupPromise;try{await popup.waitForLoadState();expect(await popup.evaluate(()=>window.opener===null)).toBe(true);expect(popup.url()).toBe('http://preview.example.invalid/article');}finally{await popup.close();}expect(remote.at(-1)).toEqual({url:'http://preview.example.invalid/article',referer:null});await page.getByRole('button',{name:'Close search',exact:true}).click();await expect(input).toHaveValue('link draft β');
 expect((await(await request.get(`/api/sessions/${id}/messages`)).json()).messages).toEqual(before);expect((await(await request.get(`/api/sessions/${id}/turns`)).json()).turns||[]).toEqual([]);await info.attach('native-links',{body:await page.screenshot(),contentType:'image/png'});
});
