import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {loadCorpus} from './support/catalogue.mjs';
const inputName='Message (Enter to send, Shift+Enter for newline)...';
test('@shared-17 canonical loaded skill Quick Action preserves draft and executes only captured session',async({page,request},info)=>{
 const scenario=loadCorpus('shared').find(s=>s.id==='@shared-17');await info.attach('gherkin',{body:scenario.steps.join('\n'),contentType:'text/plain'});
 const token=`skill-${info.project.name}-${Date.now()}`,main=await(await request.post('/api/sessions',{data:{agent_id:token,title:token}})).json(),fork=await(await request.post(`/api/sessions/${main.id}/fork`,{data:{title:token+'-other',agent_id:token+'-other'}})).json(),other={id:fork.branch.chat_jid.slice(3)};
 await page.addInitScript(id=>localStorage.setItem('gi_session_id',id),main.id);await page.goto('/');const input=page.getByRole('textbox',{name:inputName,exact:true});await expect(input).toBeVisible();await input.fill('existing request β');await page.locator('.compose-box input[type=file]').setInputFiles({name:'skill-ref.txt',mimeType:'text/plain',buffer:Buffer.from('skill media bytes')});
 const catalogue=await(await request.get('/api/quick-actions')).json();expect(catalogue.commands.filter(c=>c.name==='/skill:proof')).toEqual([{name:'/skill:proof',description:'Validate the cerulean evidence marker',source:'skill'}]);expect(catalogue.slashCommands.filter(x=>x==='/skill:proof')).toHaveLength(1);
 const palette=page.locator('.timeline-quick-actions');await input.evaluate(el=>el.blur());await page.locator('.timeline').click({position:{x:40,y:80}});await page.keyboard.type('c');await expect(palette).toBeVisible();const filter=palette.locator('.timeline-quick-actions-input');await filter.fill('proof');await expect(palette.locator('.timeline-quick-actions-item')).toHaveCount(1);await filter.fill('cerulean');await expect(palette.locator('.timeline-quick-actions-item')).toHaveCount(1);await expect(palette.locator('.timeline-quick-actions-section')).toHaveText(['Slash commands']);await expect(palette).not.toContainText('Skills');
 await palette.getByRole('button',{name:/\/skill:proof/}).click();await expect(palette).toHaveCount(0);await expect(input).toHaveValue('/skill:proof existing request β');await expect(input).toBeFocused();await expect(page.locator('.compose-box').getByText('skill-ref.txt',{exact:true})).toBeVisible();expect((await(await request.get(`/api/sessions/${main.id}/turns`)).json()).turns||[]).toEqual([]);
 let release,held=false;const gate=new Promise(r=>release=r);let posted;
 await page.route(`**/api/sessions/${main.id}/prompt`,async route=>{posted=route.request().postDataJSON();held=true;await gate;const response=await route.fetch();expect(response.status()).toBe(202);await route.fulfill({response});});
 const switchTo=async id=>{await page.getByRole('button',{name:/Manage sessions for/}).last().click();await page.locator(`[data-session-jid="gi:${id}"]`).getByRole('menuitem').click();await expect.poll(()=>page.evaluate(()=>localStorage.getItem('gi_session_id'))).toBe(id);};
 try{
  await input.press('Enter');await expect.poll(()=>held).toBe(true);await switchTo(other.id);await input.fill('other session draft');release();
  await expect.poll(async()=>((await(await request.get(`/api/sessions/${main.id}/turns`)).json()).turns||[]).length).toBe(1);const turns=(await(await request.get(`/api/sessions/${main.id}/turns`)).json()).turns;expect(turns[0].prompt).toContain('CERULEAN_NATIVE_SKILL_V1');expect(turns[0].prompt).toContain('existing request β');expect(turns[0].prompt).not.toContain('THIS_DUPLICATE');expect(turns[0].metadata.skill_name).toBe('proof');expect(turns[0].metadata.skill_command).toBe(posted.prompt);expect(turns[0].metadata.media).toHaveLength(1);expect(turns[0].metadata.media[0].session_id).toBe(main.id);expect(await(await request.get(`/api/sessions/${main.id}/media/${turns[0].metadata.media[0].media_id}`)).body()).toEqual(Buffer.from('skill media bytes'));
  await expect.poll(async()=>((await(await request.get(`/api/sessions/${main.id}/turns`)).json()).turns||[])[0]?.status).toBe('completed');const nativeMessages=(await(await request.get(`/api/sessions/${main.id}/messages`)).json()).messages||[];expect(nativeMessages.filter(m=>m.role==='user')).toHaveLength(1);expect(nativeMessages.find(m=>m.role==='assistant').content).toContain('CERULEAN_NATIVE_SKILL_V1');
  await expect(input).toHaveValue('other session draft');expect((await(await request.get(`/api/sessions/${other.id}/turns`)).json()).turns||[]).toEqual([]);await switchTo(main.id);await expect(input).toHaveValue('');await page.reload();expect((await(await request.get(`/api/sessions/${main.id}/turns`)).json()).turns).toHaveLength(1);
 }finally{release();await page.unrouteAll({behavior:'wait'});}
 // Complete the same frozen scenario with unknown/stale recovery. One tagged
 // case per project keeps the strict matrix count tied to all its assertions.
 const session=main;
 const path='.gi/skills/proof/SKILL.md',original=readFileSync('tests/ux/fixtures/skills/.gi/skills/proof/SKILL.md','utf8');
 const write=async content=>{const response=await request.post('/api/tools/execute',{data:{tool:'write',input:{path,content}}});expect((await response.json()).error).toBeFalsy();};
 try{
  await write(original+'\nCHANGED_AFTER_LOAD\n');await input.fill('/skill:proof retain draft α');await input.press('Enter');await expect(page.getByRole('alert')).toContainText('loaded skill changed');await expect(input).toHaveValue('/skill:proof retain draft α');expect((await(await request.get(`/api/sessions/${session.id}/turns`)).json()).turns||[]).toHaveLength(1);
  await input.fill('/skill:unknown recover β');await input.press('Enter');await expect(page.getByRole('alert')).toContainText('unknown or unavailable loaded skill');await expect(input).toHaveValue('/skill:unknown recover β');await page.reload();await expect(input).toHaveValue('/skill:unknown recover β');expect((await(await request.get(`/api/sessions/${session.id}/turns`)).json()).turns||[]).toHaveLength(1);
  await write(original);await input.fill('/skill:proof explicit retry');await input.press('Enter');await expect.poll(async()=>((await(await request.get(`/api/sessions/${session.id}/turns`)).json()).turns||[]).length).toBe(2);
 }finally{await write(original);}
});

test('Gi skill keyboard insertion includes trailing space and does not submit or steal later Settings focus',async({page,request},info)=>{
 const session=await(await request.post('/api/sessions',{data:{agent_id:`keyboard-${info.project.name}-${Date.now()}`,title:'keyboard skill'}})).json();await page.addInitScript(id=>localStorage.setItem('gi_session_id',id),session.id);await page.goto('/');const input=page.getByRole('textbox',{name:inputName,exact:true});await expect(input).toBeVisible();await input.evaluate(el=>el.blur());await page.getByRole('region',{name:'Conversation',exact:true}).focus();await page.keyboard.type('proof');const filter=page.locator('.timeline-quick-actions-input');await expect(filter).toBeFocused();await filter.fill('proof');await expect(page.locator('.timeline-quick-actions-item')).toHaveCount(1);await expect(page.locator('.timeline-quick-actions-item.active')).toContainText('/skill:proof');await filter.press('Enter');await expect(input).toHaveValue('/skill:proof ');await expect(input).toBeFocused();expect((await(await request.get(`/api/sessions/${session.id}/turns`)).json()).turns||[]).toEqual([]);
 await input.fill('later draft');await input.evaluate(el=>el.blur());await page.getByRole('region',{name:'Conversation',exact:true}).focus();await page.keyboard.type('proof');await expect(filter).toBeFocused();await filter.fill('proof');await expect(page.locator('.timeline-quick-actions-item.active')).toContainText('/skill:proof');await filter.evaluate(el=>{el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));window.dispatchEvent(new CustomEvent('piclaw:open-settings'));});const settings=page.getByRole('dialog',{name:'Gi Settings',exact:true});await expect(settings).toBeVisible();await expect(settings.getByRole('button',{name:'Close settings'})).toBeFocused();await expect(input).toHaveValue('/skill:proof later draft');await page.keyboard.press('Escape');await expect(input).toHaveValue('/skill:proof later draft');expect((await(await request.get(`/api/sessions/${session.id}/turns`)).json()).turns||[]).toEqual([]);
});
