import {test,expect} from 'bun:test';
import {readFileSync} from 'node:fs';
import {nextModelPanelId,modelPanelOptionId} from '../../../web/src/gi-model-accessibility.ts';
import {patchModelAccessibility} from '../../../scripts/patch-model-accessibility.mjs';
import {patchVoiceInput} from '../../../scripts/patch-voice-input.mjs';
import {patchSessionPanel} from '../../../scripts/patch-session-panel.mjs';
import {patchModelPanel} from '../../../scripts/patch-model-panel.mjs';
import {patchComposeSurface} from '../../../scripts/patch-compose-surface.mjs';
import {patchComposeCommands} from '../../../scripts/patch-compose-commands.mjs';
import {patchPickerGeometry} from '../../../scripts/patch-picker-geometry.mjs';
import {patchSkillPrefill} from '../../../scripts/patch-skill-prefill.mjs';
import {patchUploadCancel} from '../../../scripts/patch-upload-cancel.mjs';
import {patchModelPicker} from '../../../scripts/patch-model-picker.mjs';
import {patchComposePopupKeys} from '../../../scripts/patch-popup-keys.mjs';
test('model widget IDs are per mount and label encoding does not collide',()=>{
 const a=nextModelPanelId(),b=nextModelPanelId();expect(a).not.toBe(b);
 const labels=['p/name','p name','p%20name','a/b:c','p/Ω','p/"'];expect(new Set(labels.map(x=>modelPanelOptionId(a,x))).size).toBe(labels.length);
 expect(modelPanelOptionId(a,'p/name')).not.toBe(modelPanelOptionId(b,'p/name'));
});
test('guarded semantic adapter leaves source bytes and native mutation guards intact',()=>{
 const path='web/src/components/compose-box.ts',source=readFileSync(path,'utf8');
 const before=patchVoiceInput(patchSessionPanel(patchModelPanel(patchComposeSurface(patchComposeCommands(patchPickerGeometry(patchSkillPrefill(patchUploadCancel(patchModelPicker(patchComposePopupKeys(source))))))))));
 const result=patchModelAccessibility(before);
 for(const text of ['role="combobox"','role="listbox"','role="option"','tabIndex="-1"','aria-activedescendant=','aria-selected=${current','aria-disabled=${switchingModel || blocked','disabled=${switchingModel || blocked}','void handleSelectModel(modelOption)'])expect(result).toContain(text);
 expect(result.indexOf('const [loadingModels, setLoadingModels]')).toBeLessThan(result.indexOf('const modelEntries = useMemo'));
 expect(result).toContain('disabled: loadingModels || switchingModel || modelContextBlocked');
 expect(result).toContain('if (ownedModelFocus) requestAnimationFrame');
 expect(result).toContain('modelOpener?.isConnected && document.activeElement === document.body && !settingsOwnsKeyboard()');
 expect(()=>patchModelAccessibility(result)).toThrow();expect(()=>patchModelAccessibility('drift')).toThrow();expect(readFileSync(path,'utf8')).toBe(source);
});
