import {test,expect} from 'bun:test';
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';

const script=resolve(import.meta.dir,'../../../scripts/ux-parity-report.mjs');
const projects=['chromium-phone','chromium-tablet','chromium-desktop','webkit-phone','webkit-tablet','webkit-desktop'];
test('parity report keeps shared evidence separate and requires every project',()=>{
 const dir=mkdtempSync(join(tmpdir(),'gi-parity-report-'));
 try{
  const input=join(dir,'results.json');
  const spec=(id:string,count:number)=>({title:`${id} mapped test`,tests:projects.slice(0,count).map(projectName=>({projectName,results:[{status:'passed'}]}))});
  writeFileSync(input,JSON.stringify({suites:[{specs:[spec('@shared-28',6),spec('@ux-original-001',5)]}]}));
  execFileSync(process.execPath,[script,input],{cwd:dir});
  const report=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(report.scenarios).toBe(236);expect(report.sharedContractCases).toBe(42);
  expect(report.sharedCounts).toEqual({unmapped:39,pass:1,'not-run':2});expect(report.counts.pass).toBeUndefined();
  expect(report.rows.find((row:any)=>row.id==='@ux-original-001').status).toBe('partial-matrix');
  expect(report.rows.some((row:any)=>row.id==='@shared-28')).toBe(false);
  expect(report.sharedRows.find((row:any)=>row.id==='@shared-28').status).toBe('pass');
  expect(readFileSync(join(dir,'test-results/ux-parity/matrix.md'),'utf8')).toContain('Shared contract (separate evidence)');
  const steer=join(dir,'steer.json');writeFileSync(steer,JSON.stringify({suites:[{specs:[spec('@shared-30',6)]}]}));
  execFileSync(process.execPath,[script,input,steer],{cwd:dir});
  const combined=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(combined.sharedCounts).toEqual({unmapped:39,pass:2,'not-run':1});
  const sharedDeletion=join(dir,'shared-delete.json');writeFileSync(sharedDeletion,JSON.stringify({suites:[{specs:[spec('@shared-37',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,sharedDeletion],{cwd:dir});
  const withDeletion=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withDeletion.sharedCounts).toEqual({unmapped:39,pass:3});
  expect(withDeletion.sharedRows.find((row:any)=>row.id==='@shared-37').status).toBe('pass');
  expect(withDeletion.rows.find((row:any)=>row.id==='@ux-original-024').status).toBe('unmapped');
  const fit=join(dir,'fit.json');writeFileSync(fit,JSON.stringify({suites:[{specs:[spec('@ux-compaction-006',6),spec('@ux-compaction-007',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,fit],{cwd:dir});
  const all=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(all.counts.pass).toBe(2);expect(all.counts.unmapped).toBe(184);expect(all.sharedCounts.pass).toBe(2);
  const meter=join(dir,'meter.json');writeFileSync(meter,JSON.stringify({suites:[{specs:[spec('@ux-context-001',6),spec('@ux-context-005',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,fit,meter],{cwd:dir});
  const withMeter=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withMeter.counts.pass).toBe(4);expect(withMeter.counts.unmapped).toBe(184);expect(withMeter.sharedCounts.pass).toBe(2);
  const compact=join(dir,'compact.json');writeFileSync(compact,JSON.stringify({suites:[{specs:['@ux-compaction-001','@ux-compaction-002','@ux-compaction-003','@ux-compaction-004','@ux-compaction-005','@ux-context-004'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,input,steer,fit,meter,compact],{cwd:dir});
  const withCompact=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withCompact.counts.pass).toBe(10);expect(withCompact.counts.unmapped).toBe(184);
  const reconnect=join(dir,'reconnect.json');writeFileSync(reconnect,JSON.stringify({suites:[{specs:[spec('@ux-reconnect-002',6),spec('@ux-reconnect-003',6),spec('@ux-reconnect-004',6),spec('@ux-reconnect-005',6)]}]}));
  execFileSync(process.execPath,[script,reconnect],{cwd:dir});
  const reconnected=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(reconnected.counts.pass).toBe(4);expect(reconnected.counts.unmapped).toBe(184);
  const accepted=join(dir,'accepted.json');writeFileSync(accepted,JSON.stringify({suites:[{specs:['@ux-compose-007','@ux-compose-009','@ux-compose-010','@ux-compose-011'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,accepted],{cwd:dir});
  const acknowledged=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(acknowledged.counts.pass).toBe(4);expect(acknowledged.counts.unmapped).toBe(184);
  expect(acknowledged.rows.find((row:any)=>row.id==='@ux-compose-008').status).toBe('not-run');
  const references=join(dir,'references.json');writeFileSync(references,JSON.stringify({suites:[{specs:[spec('@ux-compose-008',6)]}]}));
  execFileSync(process.execPath,[script,accepted,references],{cwd:dir});
  const referenced=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(referenced.counts.pass).toBe(5);expect(referenced.counts.unmapped).toBe(184);
  expect(referenced.rows.find((row:any)=>row.id==='@ux-compose-008').status).toBe('pass');
  const rendering=join(dir,'rendering.json');writeFileSync(rendering,JSON.stringify({suites:[{specs:['@ux-timeline-023','@ux-timeline-024','@ux-original-029'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,rendering],{cwd:dir});
  const rendered=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(rendered.counts.pass).toBe(3);expect(rendered.counts.unmapped).toBe(184);
  expect(rendered.rows.find((row:any)=>row.id==='@ux-original-024').status).toBe('unmapped');
  const uploads=join(dir,'uploads.json');writeFileSync(uploads,JSON.stringify({suites:[{specs:[spec('@ux-original-026',6)]}]}));
  execFileSync(process.execPath,[script,uploads],{cwd:dir});
  const uploaded=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(uploaded.counts.pass).toBe(1);expect(uploaded.counts.unmapped).toBe(184);
  expect(uploaded.rows.find((row:any)=>row.id==='@ux-original-026').status).toBe('pass');
  expect(uploaded.rows.find((row:any)=>row.id==='@ux-compose-005').status).toBe('not-run');
  const progress=join(dir,'progress.json');writeFileSync(progress,JSON.stringify({suites:[{specs:[spec('@ux-compose-005',6)]}]}));
  execFileSync(process.execPath,[script,progress],{cwd:dir});
  const progressed=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(progressed.counts.pass).toBe(1);expect(progressed.counts.unmapped).toBe(184);
  expect(progressed.rows.find((row:any)=>row.id==='@ux-compose-005').status).toBe('pass');
  const lightbox=join(dir,'lightbox.json');writeFileSync(lightbox,JSON.stringify({suites:[{specs:['@ux-timeline-013','@ux-timeline-014','@ux-timeline-015','@ux-timeline-016'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,lightbox],{cwd:dir});
  const images=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(images.counts.pass).toBe(4);expect(images.counts.unmapped).toBe(184);
  expect(images.rows.find((row:any)=>row.id==='@ux-timeline-001').status).toBe('unmapped');
  expect(images.rows.find((row:any)=>row.id==='@ux-original-026').status).toBe('not-run');
  const preview=join(dir,'preview.json');writeFileSync(preview,JSON.stringify({suites:[{specs:[spec('@ux-workspace-008',6)]}]}));
  execFileSync(process.execPath,[script,preview],{cwd:dir});
  const workspace=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(workspace.counts.pass).toBe(1);expect(workspace.counts.unmapped).toBe(184);
  expect(workspace.rows.find((row:any)=>row.id==='@ux-workspace-009').status).toBe('unmapped');
  const tree=join(dir,'tree.json');writeFileSync(tree,JSON.stringify({suites:[{specs:[spec('@ux-workspace-004',6)]}]}));
  execFileSync(process.execPath,[script,tree],{cwd:dir});
  const hidden=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(hidden.counts.pass).toBe(1);expect(hidden.counts.unmapped).toBe(184);
  expect(hidden.rows.find((row:any)=>row.id==='@ux-workspace-005').status).toBe('unmapped');
  const deletion=join(dir,'deletion.json');writeFileSync(deletion,JSON.stringify({suites:[{specs:[spec('@ux-timeline-017',6)]}]}));
  execFileSync(process.execPath,[script,deletion],{cwd:dir});
  const deleted=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(deleted.rows.find((row:any)=>row.id==='@ux-timeline-017').status).toBe('pass');
  for(const id of ['@ux-timeline-018','@ux-timeline-020','@ux-original-024'])expect(deleted.rows.find((row:any)=>row.id===id).status).toBe('unmapped');
  expect(deleted.counts.unmapped).toBe(184);
  const dismissedPicker=join(dir,'session-dismiss.json');writeFileSync(dismissedPicker,JSON.stringify({suites:[{specs:[spec('@ux-session-006',6)]}]}));
  execFileSync(process.execPath,[script,dismissedPicker],{cwd:dir});
  const dismissed=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(dismissed.rows.find((row:any)=>row.id==='@ux-session-006').status).toBe('pass');
  for(const id of ['@ux-session-001','@ux-session-002','@ux-session-003','@ux-session-004','@ux-session-005'])expect(dismissed.rows.find((row:any)=>row.id===id).status).toBe('unmapped');
  expect(dismissed.counts.unmapped).toBe(184);
  const quick=join(dir,'quick.json');writeFileSync(quick,JSON.stringify({suites:[{specs:['@ux-original-003','@ux-original-005','@ux-original-006','@ux-original-007'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,quick],{cwd:dir});
  const quickActions=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(quickActions.counts.pass).toBe(4);expect(quickActions.counts.unmapped).toBe(184);
  for(const id of ['@ux-original-004','@ux-original-008','@ux-compose-004'])expect(quickActions.rows.find((row:any)=>row.id===id).status).toBe('unmapped');
  execFileSync(process.execPath,[script,steer,steer],{cwd:dir});
  const repeated=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(repeated.sharedRows.find((row:any)=>row.id==='@shared-30').status).toBe('partial-matrix');
  expect(repeated.sharedRows.find((row:any)=>row.id==='@shared-37').status).toBe('not-run');
 }finally{rmSync(dir,{recursive:true,force:true});}
});
