import {test,expect} from 'bun:test';
import {mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';

const script=resolve(import.meta.dir,'../../../scripts/ux-parity-report.mjs');
const projects=['chromium-phone','chromium-tablet','chromium-desktop','webkit-phone','webkit-tablet','webkit-desktop'];
test('parity report keeps shared evidence separate and requires every project',()=>{
 const dir=mkdtempSync(join(tmpdir(),'gi-parity-report-'));
 try{
  const input=join(dir,'results.json');
  const spec=(id:string,count:number)=>({title:`${id} mapped test`,tests:projects.slice(0,count).map(projectName=>({projectName,results:[{status:'passed'}]}))});
  writeFileSync(input,JSON.stringify({suites:[{specs:[spec('@shared-28',6),spec('@ux-original-001',5)]}]}));
  execFileSync(process.execPath,[script,input],{cwd:dir});
  const report=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(report.scenarios).toBe(236);expect(report.sharedContractCases).toBe(42);
  expect(report.sharedCounts).toEqual({unmapped:32,pass:1,'not-run':9});expect(report.counts.pass).toBeUndefined();
  expect(report.rows.find((row:any)=>row.id==='@ux-original-001').status).toBe('partial-matrix');
  expect(report.rows.some((row:any)=>row.id==='@shared-28')).toBe(false);
  expect(report.sharedRows.find((row:any)=>row.id==='@shared-28').status).toBe('pass');
  expect(readFileSync(join(dir,'test-results/ux-parity/matrix.md'),'utf8')).toContain('Shared contract (separate evidence)');
  const steer=join(dir,'steer.json');writeFileSync(steer,JSON.stringify({suites:[{specs:[spec('@shared-30',6)]}]}));
  execFileSync(process.execPath,[script,input,steer],{cwd:dir});
  const combined=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(combined.sharedCounts).toEqual({unmapped:32,pass:2,'not-run':8});
  const sharedDeletion=join(dir,'shared-delete.json');writeFileSync(sharedDeletion,JSON.stringify({suites:[{specs:[spec('@shared-37',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,sharedDeletion],{cwd:dir});
  const withDeletion=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withDeletion.sharedCounts).toEqual({unmapped:32,pass:3,'not-run':7});
  expect(withDeletion.sharedRows.find((row:any)=>row.id==='@shared-29').status).toBe('not-run');
  const reorder=join(dir,'shared-reorder.json');writeFileSync(reorder,JSON.stringify({suites:[{specs:[spec('@shared-29',5)]}]}));
  execFileSync(process.execPath,[script,reorder],{cwd:dir});
  expect(JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8')).sharedRows.find((row:any)=>row.id==='@shared-29').status).toBe('partial-matrix');
  writeFileSync(reorder,JSON.stringify({suites:[{specs:[spec('@shared-29',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,sharedDeletion,reorder],{cwd:dir});
  const withReorder=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withReorder.sharedCounts).toEqual({unmapped:32,pass:4,'not-run':6});
  for(const id of ['@shared-23','@shared-24'])expect(withReorder.sharedRows.find((row:any)=>row.id===id).status).toBe('not-run');
  const picker=join(dir,'shared-picker.json');writeFileSync(picker,JSON.stringify({suites:[{specs:[spec('@shared-23',6),spec('@shared-24',5)]}]}));
  execFileSync(process.execPath,[script,picker],{cwd:dir});
  const partialPicker=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(partialPicker.sharedRows.find((row:any)=>row.id==='@shared-24').status).toBe('partial-matrix');
  writeFileSync(picker,JSON.stringify({suites:[{specs:[spec('@shared-23',6),spec('@shared-24',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,sharedDeletion,reorder,picker],{cwd:dir});
  const withPicker=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withPicker.sharedCounts).toEqual({unmapped:32,pass:6,'not-run':4});
  const modelShared=join(dir,'shared-model.json');writeFileSync(modelShared,JSON.stringify({suites:[{specs:[spec('@shared-31',6),spec('@shared-32',5)]}]}));
  execFileSync(process.execPath,[script,modelShared],{cwd:dir});
  expect(JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8')).sharedRows.find((row:any)=>row.id==='@shared-32').status).toBe('partial-matrix');
  writeFileSync(modelShared,JSON.stringify({suites:[{specs:[spec('@shared-31',6),spec('@shared-32',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,sharedDeletion,reorder,picker,modelShared],{cwd:dir});
  const withModels=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withModels.sharedCounts).toEqual({unmapped:32,pass:8,'not-run':2});
  const coherent=join(dir,'shared-coherent.json');writeFileSync(coherent,JSON.stringify({suites:[{specs:[spec('@shared-25',5)]}]}));
  execFileSync(process.execPath,[script,coherent],{cwd:dir});
  expect(JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8')).sharedRows.find((row:any)=>row.id==='@shared-25').status).toBe('partial-matrix');
  writeFileSync(coherent,JSON.stringify({suites:[{specs:[spec('@shared-25',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,sharedDeletion,reorder,picker,modelShared,coherent],{cwd:dir});
  const withCoherent=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withCoherent.sharedCounts).toEqual({unmapped:32,pass:9,'not-run':1});
  const fifo=join(dir,'shared-fifo.json');writeFileSync(fifo,JSON.stringify({suites:[{specs:[spec('@shared-27',5)]}]}));
  execFileSync(process.execPath,[script,fifo],{cwd:dir});
  expect(JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8')).sharedRows.find((row:any)=>row.id==='@shared-27').status).toBe('partial-matrix');
  writeFileSync(fifo,JSON.stringify({suites:[{specs:[spec('@shared-27',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,sharedDeletion,reorder,picker,modelShared,coherent,fifo],{cwd:dir});
  const withFifo=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withFifo.sharedCounts).toEqual({unmapped:32,pass:10});
  expect(withFifo.sharedRows.find((row:any)=>row.id==='@shared-27').status).toBe('pass');
  expect(withCoherent.sharedRows.find((row:any)=>row.id==='@shared-25').status).toBe('pass');
  expect(withCoherent.sharedRows.find((row:any)=>row.id==='@shared-26').status).toBe('unmapped');
  for(const id of ['@shared-31','@shared-32'])expect(withModels.sharedRows.find((row:any)=>row.id===id).status).toBe('pass');
  expect(withModels.sharedRows.find((row:any)=>row.id==='@shared-34').status).toBe('unmapped');
  for(const id of ['@shared-23','@shared-24'])expect(withPicker.sharedRows.find((row:any)=>row.id===id).status).toBe('pass');
  expect(withPicker.sharedRows.find((row:any)=>row.id==='@shared-25').status).toBe('not-run');
  expect(withReorder.sharedRows.find((row:any)=>row.id==='@shared-29').status).toBe('pass');
  expect(withReorder.sharedRows.find((row:any)=>row.id==='@shared-27').status).toBe('not-run');
  expect(withDeletion.sharedRows.find((row:any)=>row.id==='@shared-37').status).toBe('pass');
  expect(withDeletion.rows.find((row:any)=>row.id==='@ux-original-024').status).toBe('unmapped');
  const fit=join(dir,'fit.json');writeFileSync(fit,JSON.stringify({suites:[{specs:[spec('@ux-compaction-006',6),spec('@ux-compaction-007',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,fit],{cwd:dir});
  const all=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(all.counts.pass).toBe(2);expect(all.counts.unmapped).toBe(155);expect(all.sharedCounts.pass).toBe(2);
  const meter=join(dir,'meter.json');writeFileSync(meter,JSON.stringify({suites:[{specs:[spec('@ux-context-001',6),spec('@ux-context-005',6)]}]}));
  execFileSync(process.execPath,[script,input,steer,fit,meter],{cwd:dir});
  const withMeter=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withMeter.counts.pass).toBe(4);expect(withMeter.counts.unmapped).toBe(155);expect(withMeter.sharedCounts.pass).toBe(2);
  const compact=join(dir,'compact.json');writeFileSync(compact,JSON.stringify({suites:[{specs:['@ux-compaction-001','@ux-compaction-002','@ux-compaction-003','@ux-compaction-004','@ux-compaction-005','@ux-context-004'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,input,steer,fit,meter,compact],{cwd:dir});
  const withCompact=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(withCompact.counts.pass).toBe(10);expect(withCompact.counts.unmapped).toBe(155);
  const reconnect=join(dir,'reconnect.json');writeFileSync(reconnect,JSON.stringify({suites:[{specs:[spec('@ux-reconnect-002',6),spec('@ux-reconnect-003',6),spec('@ux-reconnect-004',6),spec('@ux-reconnect-005',6)]}]}));
  execFileSync(process.execPath,[script,reconnect],{cwd:dir});
  const reconnected=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(reconnected.counts.pass).toBe(4);expect(reconnected.counts.unmapped).toBe(155);
  expect(reconnected.rows.find((row:any)=>row.id==='@ux-original-023').status).toBe('not-run');
  const stopped=join(dir,'reconnect-stop.json');writeFileSync(stopped,JSON.stringify({suites:[{specs:[spec('@ux-original-023',6)]}]}));
  execFileSync(process.execPath,[script,stopped],{cwd:dir});
  const stoppedReport=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(stoppedReport.rows.find((row:any)=>row.id==='@ux-original-023').status).toBe('pass');
  expect(stoppedReport.rows.find((row:any)=>row.id==='@ux-original-024').status).toBe('unmapped');
  expect(stoppedReport.counts.unmapped).toBe(155);
  const accepted=join(dir,'accepted.json');writeFileSync(accepted,JSON.stringify({suites:[{specs:['@ux-compose-007','@ux-compose-009','@ux-compose-010','@ux-compose-011'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,accepted],{cwd:dir});
  const acknowledged=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(acknowledged.counts.pass).toBe(4);expect(acknowledged.counts.unmapped).toBe(155);
  expect(acknowledged.rows.find((row:any)=>row.id==='@ux-compose-008').status).toBe('not-run');
  const references=join(dir,'references.json');writeFileSync(references,JSON.stringify({suites:[{specs:[spec('@ux-compose-008',6)]}]}));
  execFileSync(process.execPath,[script,accepted,references],{cwd:dir});
  const referenced=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(referenced.counts.pass).toBe(5);expect(referenced.counts.unmapped).toBe(155);
  expect(referenced.rows.find((row:any)=>row.id==='@ux-compose-008').status).toBe('pass');
  const rendering=join(dir,'rendering.json');writeFileSync(rendering,JSON.stringify({suites:[{specs:['@ux-timeline-023','@ux-timeline-024','@ux-original-029'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,rendering],{cwd:dir});
  const rendered=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(rendered.counts.pass).toBe(3);expect(rendered.counts.unmapped).toBe(155);
  expect(rendered.rows.find((row:any)=>row.id==='@ux-original-024').status).toBe('unmapped');
  const uploads=join(dir,'uploads.json');writeFileSync(uploads,JSON.stringify({suites:[{specs:[spec('@ux-original-026',6)]}]}));
  execFileSync(process.execPath,[script,uploads],{cwd:dir});
  const uploaded=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(uploaded.counts.pass).toBe(1);expect(uploaded.counts.unmapped).toBe(155);
  expect(uploaded.rows.find((row:any)=>row.id==='@ux-original-026').status).toBe('pass');
  expect(uploaded.rows.find((row:any)=>row.id==='@ux-compose-005').status).toBe('not-run');
  const progress=join(dir,'progress.json');writeFileSync(progress,JSON.stringify({suites:[{specs:[spec('@ux-compose-005',6)]}]}));
  execFileSync(process.execPath,[script,progress],{cwd:dir});
  const progressed=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(progressed.counts.pass).toBe(1);expect(progressed.counts.unmapped).toBe(155);
  expect(progressed.rows.find((row:any)=>row.id==='@ux-compose-005').status).toBe('pass');
  const lightbox=join(dir,'lightbox.json');writeFileSync(lightbox,JSON.stringify({suites:[{specs:['@ux-timeline-013','@ux-timeline-014','@ux-timeline-015','@ux-timeline-016'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,lightbox],{cwd:dir});
  const images=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(images.counts.pass).toBe(4);expect(images.counts.unmapped).toBe(155);
  expect(images.rows.find((row:any)=>row.id==='@ux-timeline-001').status).toBe('unmapped');
  expect(images.rows.find((row:any)=>row.id==='@ux-original-026').status).toBe('not-run');
  const preview=join(dir,'preview.json');writeFileSync(preview,JSON.stringify({suites:[{specs:[spec('@ux-workspace-008',6)]}]}));
  execFileSync(process.execPath,[script,preview],{cwd:dir});
  const workspace=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(workspace.counts.pass).toBe(1);expect(workspace.counts.unmapped).toBe(155);
  expect(workspace.rows.find((row:any)=>row.id==='@ux-workspace-009').status).toBe('unmapped');
  const tree=join(dir,'tree.json');writeFileSync(tree,JSON.stringify({suites:[{specs:[spec('@ux-workspace-004',6)]}]}));
  execFileSync(process.execPath,[script,tree],{cwd:dir});
  const hidden=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(hidden.counts.pass).toBe(1);expect(hidden.counts.unmapped).toBe(155);
  expect(hidden.rows.find((row:any)=>row.id==='@ux-workspace-005').status).toBe('unmapped');
  const deletion=join(dir,'deletion.json');writeFileSync(deletion,JSON.stringify({suites:[{specs:[spec('@ux-timeline-017',6)]}]}));
  execFileSync(process.execPath,[script,deletion],{cwd:dir});
  const deleted=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(deleted.rows.find((row:any)=>row.id==='@ux-timeline-017').status).toBe('pass');
  for(const id of ['@ux-timeline-018','@ux-timeline-020','@ux-original-024'])expect(deleted.rows.find((row:any)=>row.id===id).status).toBe('unmapped');
  expect(deleted.counts.unmapped).toBe(155);
  const dismissedPicker=join(dir,'session-dismiss.json');writeFileSync(dismissedPicker,JSON.stringify({suites:[{specs:[spec('@ux-session-006',6)]}]}));
  execFileSync(process.execPath,[script,dismissedPicker],{cwd:dir});
  const dismissed=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(dismissed.rows.find((row:any)=>row.id==='@ux-session-006').status).toBe('pass');
  for(const id of ['@ux-session-001','@ux-session-002','@ux-session-003','@ux-session-004','@ux-session-005'])expect(dismissed.rows.find((row:any)=>row.id===id).status).toBe('not-run');
  expect(dismissed.counts.unmapped).toBe(155);
  const filteredPicker=join(dir,'session-filter.json');writeFileSync(filteredPicker,JSON.stringify({suites:[{specs:[spec('@ux-session-003',6)]}]}));
  execFileSync(process.execPath,[script,filteredPicker],{cwd:dir});
  const filtered=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(filtered.rows.find((row:any)=>row.id==='@ux-session-003').status).toBe('pass');
  expect(filtered.rows.find((row:any)=>row.id==='@ux-session-002').status).toBe('not-run');
  expect(filtered.counts.unmapped).toBe(155);
  const selectedTimeline=join(dir,'selected-timeline.json');writeFileSync(selectedTimeline,JSON.stringify({suites:[{specs:[spec('@ux-session-001',6)]}]}));
  execFileSync(process.execPath,[script,selectedTimeline],{cwd:dir});
  const selectedChat=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(selectedChat.rows.find((row:any)=>row.id==='@ux-session-001').status).toBe('pass');
  expect(selectedChat.rows.find((row:any)=>row.id==='@ux-session-002').status).toBe('not-run');
  expect(selectedChat.counts.unmapped).toBe(155);
  const archiveRestore=join(dir,'session-archive.json');writeFileSync(archiveRestore,JSON.stringify({suites:[{specs:[spec('@ux-session-004',6)]}]}));
  execFileSync(process.execPath,[script,archiveRestore],{cwd:dir});
  const archived=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(archived.rows.find((row:any)=>row.id==='@ux-session-004').status).toBe('pass');
  expect(archived.rows.find((row:any)=>row.id==='@ux-session-002').status).toBe('not-run');
  expect(archived.counts.unmapped).toBe(155);
  const groupedPicker=join(dir,'session-groups.json');writeFileSync(groupedPicker,JSON.stringify({suites:[{specs:[spec('@ux-session-002',6)]}]}));
  execFileSync(process.execPath,[script,groupedPicker],{cwd:dir});
  const grouped=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(grouped.rows.find((row:any)=>row.id==='@ux-session-002').status).toBe('pass');
  expect(grouped.rows.find((row:any)=>row.id==='@ux-session-005').status).toBe('not-run');
  expect(grouped.counts.unmapped).toBe(155);
  const swipe=join(dir,'session-swipe.json');writeFileSync(swipe,JSON.stringify({suites:[{specs:[spec('@ux-session-005',6)]}]}));
  execFileSync(process.execPath,[script,swipe],{cwd:dir});
  const swiped=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(swiped.rows.find((row:any)=>row.id==='@ux-session-005').status).toBe('pass');
  expect(swiped.rows.find((row:any)=>row.id==='@ux-mobile-001').status).toBe('not-run');
  expect(swiped.counts.unmapped).toBe(155);
  const wrap=join(dir,'mobile-swipe-wrap.json');writeFileSync(wrap,JSON.stringify({suites:[{specs:[spec('@ux-mobile-001',6)]}]}));
  execFileSync(process.execPath,[script,wrap],{cwd:dir});
  const wrapped=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(wrapped.rows.find((row:any)=>row.id==='@ux-mobile-001').status).toBe('pass');
  expect(wrapped.rows.find((row:any)=>row.id==='@ux-mobile-002').status).toBe('unmapped');
  expect(wrapped.rows.find((row:any)=>row.id==='@ux-mobile-005').status).toBe('not-run');
  expect(wrapped.counts.unmapped).toBe(155);
  expect(wrapped.rows.find((row:any)=>row.id==='@ux-mobile-004').status).toBe('not-run');
  const mobileOrder=join(dir,'mobile-order.json');writeFileSync(mobileOrder,JSON.stringify({suites:[{specs:[spec('@ux-mobile-004',6)]}]}));
  execFileSync(process.execPath,[script,mobileOrder],{cwd:dir});
  const ordered=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(ordered.rows.find((row:any)=>row.id==='@ux-mobile-004').status).toBe('pass');
  expect(ordered.rows.find((row:any)=>row.id==='@ux-mobile-002').status).toBe('unmapped');
  expect(ordered.counts.unmapped).toBe(155);
  const vertical=join(dir,'mobile-vertical.json');writeFileSync(vertical,JSON.stringify({suites:[{specs:[spec('@ux-mobile-005',6)]}]}));
  execFileSync(process.execPath,[script,vertical],{cwd:dir});
  const cancelled=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(cancelled.rows.find((row:any)=>row.id==='@ux-mobile-005').status).toBe('pass');
  expect(cancelled.rows.find((row:any)=>row.id==='@ux-mobile-003').status).toBe('not-run');
  expect(cancelled.rows.find((row:any)=>row.id==='@ux-mobile-006').status).toBe('not-run');
  expect(cancelled.counts.unmapped).toBe(155);
  const panels=join(dir,'mobile-panels.json');writeFileSync(panels,JSON.stringify({suites:[{specs:[spec('@ux-mobile-003',6)]}]}));
  execFileSync(process.execPath,[script,panels],{cwd:dir});
  const passedPanels=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(passedPanels.rows.find((row:any)=>row.id==='@ux-mobile-003').status).toBe('pass');
  expect(passedPanels.rows.find((row:any)=>row.id==='@ux-mobile-002').status).toBe('unmapped');
  const wheel=join(dir,'mobile-safari-wheel.json');writeFileSync(wheel,JSON.stringify({suites:[{specs:[spec('@ux-mobile-006',6)]}]}));
  execFileSync(process.execPath,[script,wheel],{cwd:dir});
  const wheeled=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(wheeled.rows.find((row:any)=>row.id==='@ux-mobile-006').status).toBe('pass');
  expect(wheeled.rows.find((row:any)=>row.id==='@ux-mobile-004').status).toBe('not-run');
  expect(wheeled.rows.find((row:any)=>row.id==='@ux-pwa-001').status).toBe('not-run');
  expect(wheeled.counts.unmapped).toBe(155);
  const manifest=join(dir,'pwa-manifest.json');writeFileSync(manifest,JSON.stringify({suites:[{specs:[spec('@ux-pwa-001',6)]}]}));
  execFileSync(process.execPath,[script,manifest],{cwd:dir});
  const installed=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(installed.rows.find((row:any)=>row.id==='@ux-pwa-001').status).toBe('pass');
  expect(installed.rows.find((row:any)=>row.id==='@ux-pwa-002').status).toBe('unmapped');
  expect(installed.counts.unmapped).toBe(155);
  const settingsIds=['@ux-settings-layering-001','@ux-settings-layering-002','@ux-settings-layering-003','@ux-settings-layering-004','@ux-settings-dialog-001','@ux-settings-dialog-003','@ux-settings-dialog-004'];
  for(const id of settingsIds)expect(installed.rows.find((row:any)=>row.id===id).status).toBe('not-run');
  const settings=join(dir,'settings-shell.json');writeFileSync(settings,JSON.stringify({suites:[{specs:settingsIds.map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,settings],{cwd:dir});
  const shelled=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  for(const id of settingsIds)expect(shelled.rows.find((row:any)=>row.id===id).status).toBe('pass');
  for(const id of ['@ux-settings-dialog-002','@ux-settings-007'])expect(shelled.rows.find((row:any)=>row.id===id).status).toBe('unmapped');
  const lazyIds=['@ux-settings-dialog-005','@ux-settings-003'];
  for(const id of lazyIds)expect(shelled.rows.find((row:any)=>row.id===id).status).toBe('not-run');
  const lazy=join(dir,'settings-lazy.json');writeFileSync(lazy,JSON.stringify({suites:[{specs:lazyIds.map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,lazy],{cwd:dir});
  const loaded=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  for(const id of lazyIds)expect(loaded.rows.find((row:any)=>row.id===id).status).toBe('pass');
  expect(loaded.rows.find((row:any)=>row.id==='@ux-settings-dialog-002').status).toBe('unmapped');
  expect(loaded.counts.unmapped).toBe(155);
  expect(shelled.counts.unmapped).toBe(155);
  expect(loaded.rows.find((row:any)=>row.id==='@ux-settings-004').status).toBe('not-run');
  const header=join(dir,'settings-header.json');writeFileSync(header,JSON.stringify({suites:[{specs:[spec('@ux-settings-004',6)]}]}));
  execFileSync(process.execPath,[script,header],{cwd:dir});
  const resized=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(resized.rows.find((row:any)=>row.id==='@ux-settings-004').status).toBe('pass');
  expect(resized.rows.find((row:any)=>row.id==='@ux-settings-009').status).toBe('unmapped');
  expect(resized.counts.unmapped).toBe(155);
  const thoughtsIds=['@ux-thoughts-001','@ux-thoughts-002','@ux-thoughts-003','@ux-thoughts-004','@ux-thoughts-005'];
  for(const id of thoughtsIds)expect(resized.rows.find((row:any)=>row.id===id).status).toBe('not-run');
  const thoughts=join(dir,'thoughts.json');writeFileSync(thoughts,JSON.stringify({suites:[{specs:thoughtsIds.map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,thoughts],{cwd:dir});
  const disclosed=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(disclosed.counts.pass).toBe(5);expect(disclosed.counts.unmapped).toBe(155);
  for(const id of thoughtsIds)expect(disclosed.rows.find((row:any)=>row.id===id).status).toBe('pass');
  const modelPicker=join(dir,'model-picker.json');writeFileSync(modelPicker,JSON.stringify({suites:[{specs:[spec('@ux-original-020',6)]}]}));
  execFileSync(process.execPath,[script,modelPicker],{cwd:dir});
  const picked=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(picked.rows.find((row:any)=>row.id==='@ux-original-020').status).toBe('pass');
  expect(picked.rows.find((row:any)=>row.id==='@ux-original-022').status).toBe('not-run');
  expect(picked.counts.unmapped).toBe(155);
  const sparseModel=join(dir,'sparse-model.json');writeFileSync(sparseModel,JSON.stringify({suites:[{specs:[spec('@ux-original-022',6)]}]}));
  execFileSync(process.execPath,[script,sparseModel],{cwd:dir});
  const sparse=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(sparse.rows.find((row:any)=>row.id==='@ux-original-022').status).toBe('pass');
  expect(sparse.rows.find((row:any)=>row.id==='@ux-original-024').status).toBe('unmapped');
  expect(sparse.counts.unmapped).toBe(155);
  const quick=join(dir,'quick.json');writeFileSync(quick,JSON.stringify({suites:[{specs:['@ux-original-003','@ux-original-005','@ux-original-006','@ux-original-007'].map(id=>spec(id,6))}]}));
  execFileSync(process.execPath,[script,quick],{cwd:dir});
  const quickActions=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(quickActions.counts.pass).toBe(4);expect(quickActions.counts.unmapped).toBe(155);
  for(const id of ['@ux-original-004','@ux-original-008','@ux-compose-004'])expect(quickActions.rows.find((row:any)=>row.id===id).status).toBe('unmapped');
  execFileSync(process.execPath,[script,steer,steer],{cwd:dir});
  const repeated=JSON.parse(readFileSync(join(dir,'test-results/ux-parity/matrix.json'),'utf8'));
  expect(repeated.sharedRows.find((row:any)=>row.id==='@shared-30').status).toBe('partial-matrix');
  expect(repeated.sharedRows.find((row:any)=>row.id==='@shared-37').status).toBe('not-run');
 }finally{rmSync(dir,{recursive:true,force:true});}
});
