import { defineConfig } from '@playwright/test';

const sizes = { phone: { width: 390, height: 844 }, tablet: { width: 820, height: 1180 }, desktop: { width: 1440, height: 900 } };
if (!process.env.GI_TEST_RUN_ROOT) throw new Error("Use scripts/run-playwright.sh or make");
const results = process.env.GI_TEST_RUN_ROOT + "/results/ux-parity";

export default defineConfig({
  testDir: './tests/web-regression', testMatch: process.env.GI_WEB_REGRESSION_LIST_ALL ? ['*.spec.mjs'] : process.env.GI_UX_DIRECT_REPLY_STEER ? ['direct-reply-steer.spec.mjs'] : process.env.GI_UX_CARD_IDENTITY ? ['card-submission-identity.spec.mjs'] : process.env.GI_UX_BTW_MOUNT ? ['btw-mount.spec.mjs'] : process.env.GI_UX_WIDGETS ? ['widget-persisted.spec.mjs'] : process.env.GI_UX_COMPOSE_ESCAPE ? ['compose-escape.spec.mjs'] : process.env.GI_UX_ENDED_STEER ? ['queue-ended-steer.spec.mjs'] : process.env.GI_UX_PICKER_THINKING ? ['picker-thinking.spec.mjs'] : process.env.GI_UX_MESSAGE_RETRIEVAL ? ['message-retrieval.spec.mjs'] : process.env.GI_UX_THINKING ? ['session-thinking.spec.mjs'] : process.env.GI_UX_BASIC_HTTP ? ['basic-http-control.spec.mjs'] : process.env.GI_UX_NOTIFICATIONS ? ['notifications.spec.mjs'] : process.env.GI_UX_VOICE_INPUT ? ['voice-input.spec.mjs'] : process.env.GI_UX_SESSION_PANEL ? ['session-panel.spec.mjs'] : process.env.GI_UX_MODEL_PANEL ? ['model-panel.spec.mjs'] : process.env.GI_UX_COMPOSE_SURFACE ? ['compose-surface.spec.mjs'] : process.env.GI_UX_SLASH ? ['slash-ownership.spec.mjs'] : process.env.GI_UX_PICKER_GEOMETRY ? ['picker-geometry.spec.mjs'] : process.env.GI_UX_JOURNEY ? ['startup-journey.spec.mjs'] : process.env.GI_UX_PASSKEYS ? ['passkeys.spec.mjs'] : process.env.GI_UX_AUTH ? ["auth.spec.mjs"] : process.env.GI_UX_SKILLS ? ['skills.spec.mjs'] : process.env.GI_UX_THOUGHTS ? ['thoughts.spec.mjs'] : process.env.GI_UX_STATUS_SWIPES ? ['status-swipes.spec.mjs'] : process.env.GI_UX_MOBILE_EXCLUSIONS ? ['mobile-exclusions.spec.mjs'] : process.env.GI_UX_PROVIDERS ? ['gi-providers.spec.mjs'] : process.env.GI_UX_INDEX_CONFIG ? ['workspace-index-config.spec.mjs'] : process.env.GI_UX_RECONNECT ? ['reconnect.spec.mjs'] : process.env.GI_UX_COMPACTION ? ['compaction.spec.mjs'] : process.env.GI_UX_METER ? ['context-meter.spec.mjs'] : process.env.GI_UX_CONTEXT ? ['context-fit.spec.mjs'] : process.env.GI_UX_STEER ? ['queue-steer.spec.mjs'] : ["card-rejection.spec.mjs","recovery-placeholders.spec.mjs","recovery-controls.spec.mjs","outcomes.spec.mjs","remote-links.spec.mjs","tool-activity.spec.mjs","queue-idle-steer.spec.mjs","speech-contract.spec.mjs","speech.spec.mjs","message-delete.spec.mjs","message-copy.spec.mjs","quick-actions.spec.mjs","classic.spec.mjs","shell.spec.mjs","settings-shell.spec.mjs","gi-settings.spec.mjs","pwa.spec.mjs","session.spec.mjs","drafts.spec.mjs","queue.spec.mjs","models.spec.mjs","context.spec.mjs","queue-return.spec.mjs","rendering.spec.mjs","lightbox.spec.mjs","workspace-preview.spec.mjs","workspace-tabs.spec.mjs","pane-host.spec.mjs"], timeout: 30000,
  expect: { timeout: 4000 }, retries: 0, workers: 1,
  outputDir: `${results}/artifacts`,
  reporter: [['line'], ['json', { outputFile: process.env.GI_UX_MESSAGE_RETRIEVAL ? `${results}/message-retrieval-results.json` : process.env.GI_UX_BASIC_HTTP ? `${results}/basic-http-results.json` : process.env.GI_UX_NOTIFICATIONS ? `${results}/notifications-results.json` : process.env.GI_UX_VOICE_INPUT ? `${results}/voice-input-results.json` : process.env.GI_UX_SESSION_PANEL ? `${results}/session-panel-results.json` : process.env.GI_UX_MODEL_PANEL ? `${results}/model-panel-results.json` : process.env.GI_UX_COMPOSE_SURFACE ? `${results}/compose-surface-results.json` : process.env.GI_UX_SLASH ? `${results}/slash-results.json` : process.env.GI_UX_PICKER_GEOMETRY ? `${results}/picker-geometry-results.json` : process.env.GI_UX_JOURNEY ? `${results}/journey-results.json` : process.env.GI_UX_THOUGHTS ? `${results}/thoughts-results.json` : process.env.GI_UX_STATUS_SWIPES ? `${results}/status-swipes-results.json` : process.env.GI_UX_PROVIDERS ? `${results}/gi-providers-results.json` : process.env.GI_UX_SHARED_COPY_DELETE ? `${results}/shared-copy-delete-results.json` : process.env.GI_UX_INDEX_CONFIG ? `${results}/index-config-results.json` : process.env.GI_UX_RECONNECT ? `${results}/reconnect-results.json` : process.env.GI_UX_COMPACTION ? `${results}/compaction-results.json` : process.env.GI_UX_METER ? `${results}/context-meter-results.json` : process.env.GI_UX_CONTEXT ? `${results}/context-fit-results.json` : process.env.GI_UX_STEER ? `${results}/steer-results.json` : `${results}/results.json` }]],
  use: {
    baseURL: process.env.GI_TEST_URL || 'http://127.0.0.1:19091',
    serviceWorkers: 'block', headless: true,
    trace: 'retain-on-failure', screenshot: 'only-on-failure',
  },
  projects: ['chromium', 'webkit'].flatMap(browserName => Object.entries(sizes).map(([size, viewport]) => ({
    name: `${browserName}-${size}`, use: { browserName, viewport },
  }))),
});
