// @ts-nocheck
const THEME_STORAGE_KEY = 'piclaw_theme';
const TINT_STORAGE_KEY = 'piclaw_tint';
const DEFAULT_LIGHT = { bgPrimary:'#ffffff', bgSecondary:'#f7f9fa', bgHover:'#e8ebed', textPrimary:'#0f1419', textSecondary:'#536471', borderColor:'#eff3f4', accent:'#1d9bf0', accentHover:'#1a8cd8', warning:'#f0b429', danger:'#f4212e', success:'#00ba7c' };
const DEFAULT_DARK = { bgPrimary:'#000000', bgSecondary:'#16181c', bgHover:'#1d1f23', textPrimary:'#e7e9ea', textSecondary:'#71767b', borderColor:'#2f3336', accent:'#1d9bf0', accentHover:'#1a8cd8', warning:'#f0b429', danger:'#f4212e', success:'#00ba7c' };
export const THEME_PRESETS = { default:{label:'Default',mode:'auto',light:DEFAULT_LIGHT,dark:DEFAULT_DARK}, dracula:{label:'Dracula',mode:'dark',dark:{bgPrimary:'#282a36',bgSecondary:'#303445',bgHover:'#3a3f52',textPrimary:'#f8f8f2',textSecondary:'#c5c8d6',borderColor:'#44475a',accent:'#bd93f9',accentHover:'#a87ded',danger:'#ff5555',success:'#50fa7b'}}, nord:{label:'Nord',mode:'dark',dark:{bgPrimary:'#2e3440',bgSecondary:'#3b4252',bgHover:'#434c5e',textPrimary:'#eceff4',textSecondary:'#d8dee9',borderColor:'#4c566a',accent:'#88c0d0',accentHover:'#78a9c0',danger:'#bf616a',success:'#a3be8c'}}, github:{label:'GitHub',mode:'auto',light:{bgPrimary:'#ffffff',bgSecondary:'#f6f8fa',bgHover:'#eaeef2',textPrimary:'#24292f',textSecondary:'#57606a',borderColor:'#d0d7de',accent:'#0969da',accentHover:'#0550ae',danger:'#cf222e',success:'#1a7f37'},dark:{bgPrimary:'#0d1117',bgSecondary:'#161b22',bgHover:'#21262d',textPrimary:'#c9d1d9',textSecondary:'#8b949e',borderColor:'#30363d',accent:'#2f81f7',accentHover:'#1f6feb',danger:'#f85149',success:'#3fb950'}} };
const TINTS = [null, '#3b82f6', '#f59e0b', '#10b981', '#ef4444'];
let currentTheme = { theme:'default', tint:null };
let currentMode = 'light';
let mediaListenerAttached = false;
function getLocalStorageItem(key){ try{return localStorage.getItem(key);}catch{return null;} }
function setLocalStorageItem(key,value){ try{localStorage.setItem(key,value);}catch{} }
function normalizeThemeName(name){ return THEME_PRESETS[name] ? name : 'default'; }
function parseHexColor(input){ if(!input) return null; const raw=String(input).trim(); const hex=raw.startsWith('#')?raw.slice(1):raw; if(!/^[0-9a-fA-F]{6}$/.test(hex)) return null; const int=parseInt(hex,16); return { r:(int>>16)&255,g:(int>>8)&255,b:int&255,hex:`#${hex.toLowerCase()}`}; }
function mixColors(base, overlay, ratio){ const r=Math.round(base.r+(overlay.r-base.r)*ratio); const g=Math.round(base.g+(overlay.g-base.g)*ratio); const b=Math.round(base.b+(overlay.b-base.b)*ratio); return `rgb(${r} ${g} ${b})`; }
function rgbaColor(color, alpha){ return `rgba(${color.r}, ${color.g}, ${color.b}, ${alpha})`; }
function resolveSystemMode(){ return window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'; }
function resolvePreset(name){ return THEME_PRESETS[name] || THEME_PRESETS.default; }
function resolveModeForPreset(preset){ return preset.mode === 'auto' ? resolveSystemMode() : preset.mode; }
function resolvePalette(themeName, mode){ const preset = resolvePreset(themeName); return preset[mode] || preset.light || preset.dark || DEFAULT_LIGHT; }
function buildTintedPalette(basePalette, tintHex){ const tint = parseHexColor(tintHex); if(!tint) return basePalette; const parseCss=(value)=>parseHexColor(String(value).replace('#',''))||tint; const bgPrimary=parseCss(basePalette.bgPrimary); const bgSecondary=parseCss(basePalette.bgSecondary); const bgHover=parseCss(basePalette.bgHover); const textPrimary=parseCss(basePalette.textPrimary); const textSecondary=parseCss(basePalette.textSecondary); const borderColor=parseCss(basePalette.borderColor); const warning=parseCss(basePalette.warning||DEFAULT_LIGHT.warning); const danger=parseCss(basePalette.danger); const success=parseCss(basePalette.success); return { ...basePalette, bgPrimary:mixColors(bgPrimary,tint,0.08), bgSecondary:mixColors(bgSecondary,tint,0.12), bgHover:mixColors(bgHover,tint,0.16), textPrimary:mixColors(textPrimary,tint,0.06), textSecondary:mixColors(textSecondary,tint,0.1), borderColor:mixColors(borderColor,tint,0.1), accent:tint.hex, accentHover:mixColors(tint, parseHexColor('ffffff'), 0.18), warning:mixColors(warning,tint,0.14), danger:mixColors(danger,tint,0.16), success:mixColors(success,tint,0.16) }; }
function applyCssVariables(palette, mode){ const root=document.documentElement; const accentHex=parseHexColor((palette.accent||'#1d9bf0').replace('#','')) || parseHexColor('1d9bf0'); const vars={ '--bg-primary':palette.bgPrimary,'--bg-secondary':palette.bgSecondary,'--bg-hover':palette.bgHover,'--text-primary':palette.textPrimary,'--text-secondary':palette.textSecondary,'--border-color':palette.borderColor,'--accent-color':palette.accent,'--accent-hover':palette.accentHover||palette.accent,'--accent-color-alpha':rgbaColor(accentHex, mode==='dark'?0.35:0.25),'--accent-soft':rgbaColor(accentHex, mode==='dark'?0.16:0.12),'--accent-soft-strong':rgbaColor(accentHex, mode==='dark'?0.28:0.2),'--warning-color':palette.warning||DEFAULT_LIGHT.warning,'--danger-color':palette.danger||DEFAULT_LIGHT.danger,'--success-color':palette.success||DEFAULT_LIGHT.success,'--search-highlight-color':rgbaColor(accentHex, mode==='dark'?0.35:0.2)}; Object.entries(vars).forEach(([k,v])=>root.style.setProperty(k,v)); }
function applyThemeState(nextTheme, options={}){ const themeName=normalizeThemeName(nextTheme?.theme||'default'); const tint=nextTheme?.tint?String(nextTheme.tint).trim():null; currentTheme={theme:themeName,tint}; currentMode=resolveModeForPreset(resolvePreset(themeName)); const root=document.documentElement; root.dataset.theme=currentMode; root.dataset.colorTheme=themeName; root.dataset.tint=tint||''; root.style.colorScheme=currentMode; if(currentMode==='dark'){root.classList.add('dark'); root.classList.remove('light');} else {root.classList.add('light'); root.classList.remove('dark');} let palette = resolvePalette(themeName,currentMode); if(themeName==='default' && tint) palette = buildTintedPalette(palette,tint); applyCssVariables(palette,currentMode); if(options.persist!==false){ setLocalStorageItem(THEME_STORAGE_KEY, themeName); setLocalStorageItem(TINT_STORAGE_KEY, tint||''); } window.dispatchEvent(new CustomEvent('piclaw-theme-change',{detail:{...currentTheme,mode:currentMode}})); }
function handleSystemThemeChange(){ if(resolvePreset(currentTheme.theme).mode!=='auto') return; applyThemeState(currentTheme,{persist:false}); }
export function initTheme(){ const storedTheme = normalizeThemeName(getLocalStorageItem(THEME_STORAGE_KEY)||'default'); const storedTint = getLocalStorageItem(TINT_STORAGE_KEY)||null; applyThemeState({theme:storedTheme,tint:storedTint},{persist:false}); if(window.matchMedia && !mediaListenerAttached){ const media=window.matchMedia('(prefers-color-scheme: dark)'); const fn=()=>handleSystemThemeChange(); if(media.addEventListener) media.addEventListener('change',fn); else if(media.addListener) media.addListener(fn); mediaListenerAttached=true; return ()=>{ if(media.removeEventListener) media.removeEventListener('change',fn); else if(media.removeListener) media.removeListener(fn); mediaListenerAttached=false; }; } return ()=>{}; }
export function cycleThemePreset(){ const names=Object.keys(THEME_PRESETS); const currentIndex=names.indexOf(currentTheme.theme); const next=names[(currentIndex+1)%names.length]||'default'; applyThemeState({theme:next,tint:currentTheme.tint},{persist:true}); return next; }
export function cycleTint(){ const currentIndex=TINTS.findIndex((t)=>t===currentTheme.tint); const next=TINTS[(currentIndex+1)%TINTS.length]; applyThemeState({theme:currentTheme.theme,tint:next},{persist:true}); return next; }
export function getCurrentThemeLabel(){ return resolvePreset(currentTheme.theme).label; }
export function getCurrentTintLabel(){ return currentTheme.tint || 'off'; }
